sudo: false
dist: trusty
language: java
jdk:
  - openjdk11

cache:
  directories:
  - "$HOME/.cache"

before_install:
  - cp ./.mvn/ci-settings.xml $HOME/.m2/settings.xml

build:
  provider: script
  script: "mvn -P ci install"
  skip_cleanup: false
  condition: "!(tag = ^v*$ OR branch = master)"

deploy:
  provider: script
  script: "mvn -P ci deploy"
  skip_cleanup: false
  condition: "tag = ^v*$ OR branch = master"
