sudo: false
dist: trusty
language: java
jdk:
  - openjdk11

cache:
  directories:
  - "$HOME/.cache"

before_install:
  - cp ./.mvn/ci-settings.xml $HOME/.m2/settings.xml
  - wget http://apache.mirror.gtcomm.net/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzvf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
  - mvn -v


script: "mvn -P ci install"

deploy:
  provider: script
  script: "mvn -P ci deploy -DskipTests  -s $HOME/.m2/settings.xml"
  skip_cleanup: false
  on:
    tags: true
    branch: master
